version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    # Workflow files stored in the default location of `.github/workflows`
    directory: '/'
    # Check for updates to GitHub Actions every weekday
    schedule:
      interval: 'weekly'

  # Maintain dependencies for npm
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    # Check the npm registry for updates every weekday
    schedule:
      interval: 'weekly'
